import type { FraudCase } from '@/types/case'

export const FRAUD_CASES: FraudCase[] = [
  {
    id: 'case-wh-001',
    title: '武汉：好心担保变成50万元实际借款人',
    city: '武汉市',
    region: '华中',
    scamType: '熟人担保转借款',
    riskLevel: '高',
    progress: '已判决',
    amountLoss: 500000,
    publishedAt: '2025-12-09',
    updatedAt: '2026-06-10',
    summary: '公开检察案例显示，张女士原以为只是帮发小担保10万元购车贷款，在线下中介公司被诱导签下50万元借贷合同，并被承诺后续会转到对方名下，最终成为法律上的借款人。',
    pattern: ['熟人求助', '担保人变借款人', '承诺后续转名'],
    warningSignals: ['贷款金额突然变大', '中介和熟人共同劝说签字', '声称几个月后可转到A名下'],
    suggestions: ['拒绝用本人身份替他人申请贷款', '签字前核对合同借款人和金额', '保留聊天、合同、面签录像等材料'],
    timeline: [
      { time: '2024-07', event: '熟人称资质不足，希望借助张女士征信贷款' },
      { time: '办理当天', event: '中介将约定的10万元改为50万元借贷合同' },
      { time: '贷款后', event: '资金由A使用，B承担还款压力' },
      { time: '2025-08', event: '法院以诈骗罪对涉案人员作出判决' },
    ],
    sourceName: '武汉市人民检察院公开案例',
    sourceUrl: 'https://wh.hbjc.gov.cn/wjxw/yasf/202512/t20251209_1874960.shtml',
    credibility: '高',
  },
  {
    id: 'case-sh-002',
    title: '上海松江：帮熟人贷款背上70余万元债务',
    city: '上海市',
    region: '华东',
    scamType: '监管人话术',
    riskLevel: '高',
    progress: '立案中',
    amountLoss: 700000,
    publishedAt: '2026-04-22',
    updatedAt: '2026-06-10',
    summary: '松江法院公开审理的AB贷套路诈骗案中，被害人被熟人和贷款中介引导，以“帮忙”“监管人”等话术进入贷款流程，最终贷款资金由他人使用，自己承担债务风险。',
    pattern: ['监管人包装', '线下中介操作', '贷款资金转给A'],
    warningSignals: ['称B不需要还款', '要求配合刷脸、签字、面签', '贷款用途和资金流向不一致'],
    suggestions: ['不做“监管人”“名义借款人”', '拒绝帮他人过桥或过账', '发现资金流向异常立即报警并联系放款机构'],
    timeline: [
      { time: '贷款前', event: '熟人打造用款理由并引入中介' },
      { time: '办理中', event: '中介配合完成贷款材料和面签流程' },
      { time: '放款后', event: '资金实际由A使用，B承担还款责任' },
      { time: '2026-04', event: '法院公开审理并开展以案释法' },
    ],
    sourceName: '上海松江区政府公开庭审报道',
    sourceUrl: 'https://www.songjiang.gov.cn/xwzx/001001/20260422/7c093077-6883-406f-b0e8-ebf7480c4233.html',
    credibility: '高',
  },
  {
    id: 'case-gz-003',
    title: '广州花都：黑中介以“帮忙拉升信用”诱导B申请贷款',
    city: '广州市',
    region: '华南',
    scamType: '拉升信用分',
    riskLevel: '高',
    progress: '待核验',
    amountLoss: 244000,
    publishedAt: '2025-02-07',
    updatedAt: '2026-06-10',
    summary: '地方金融风险提示明确指出，AB贷本质是诈骗：贷款业务审核实际申请人的资质，绝不是让B申请贷款给A使用。B若配合申请，可能在A失联后承担全部还款责任。',
    pattern: ['拉升信用分', '担保人变主借人', '资金由A使用'],
    warningSignals: ['请求“帮忙走流程”', '承诺不影响征信', '要求用B身份信息申请贷款'],
    suggestions: ['向亲友解释AB贷风险并拒绝配合', '只通过持牌机构办理本人真实贷款', '发现黑中介及时举报'],
    timeline: [
      { time: '接触阶段', event: 'A称自身资质不足，请B帮忙提升信用或担保' },
      { time: '办理阶段', event: '中介使用B的身份信息申请贷款' },
      { time: '放款阶段', event: '贷款资金交由A使用或被中介抽取服务费' },
      { time: '逾期阶段', event: 'A无法还款后，B作为借款人被追偿' },
    ],
    sourceName: '广州市花都区人民政府金融风险提示',
    sourceUrl: 'https://www.huadu.gov.cn/gzhdjr/gkmlpt/content/10/10100/post_10100899.html',
    credibility: '高',
  },
  {
    id: 'case-sz-004',
    title: '深圳监管提示：不法中介诱导担保人B背债',
    city: '深圳市',
    region: '华南',
    scamType: '非法贷款中介',
    riskLevel: '高',
    progress: '待核验',
    amountLoss: 43000,
    publishedAt: '2025-03-15',
    updatedAt: '2026-06-10',
    summary: '国家金融监督管理总局深圳监管局提示，不法贷款中介会以“可为信用不良客户办理无担保贷款”为噱头，诱导借款人陷入AB贷款陷阱，使用担保人B的身份信息申请贷款。',
    pattern: ['无担保贷款噱头', '高额服务费', 'B无获利却背债'],
    warningSignals: ['黑中介承诺包批包过', '要求找征信好的亲友', '服务费按贷款金额高比例收取'],
    suggestions: ['核验机构是否持牌', '拒绝高额前置服务费', '不要把身份证、银行卡、人脸识别交给中介操作'],
    timeline: [
      { time: '获客阶段', event: '中介用“信用差也能办”吸引A' },
      { time: '转化阶段', event: '要求A寻找资质更好的B参与办理' },
      { time: '签约阶段', event: 'B以为是担保，实际成为借款人' },
      { time: '还款阶段', event: 'A不还款时，B承担违约和征信风险' },
    ],
    sourceName: '国家金融监督管理总局深圳监管局风险提示',
    sourceUrl: 'https://www.nfra.gov.cn/branch/shenzhen/view/pages/common/ItemDetail.html?docId=1212987&itemId=1041',
    credibility: '高',
  },
  {
    id: 'case-bj-005',
    title: '北京：非法贷款中介“AB套路骗亲友”风险提示',
    city: '北京市',
    region: '华北',
    scamType: '亲友代贷',
    riskLevel: '中',
    progress: '待核验',
    amountLoss: 180000,
    publishedAt: '2025-10-31',
    updatedAt: '2026-06-10',
    summary: '北京金融监管风险提示将“AB套路骗亲友”列为非法贷款中介陷阱之一：实际用款人A无法获取贷款时，中介要求A委托资质较好的亲友B申请贷款，贷款归A使用，还款责任由B承担。',
    pattern: ['亲友代贷', '还款责任转移', '贷后合规话术'],
    warningSignals: ['称只是帮忙不承担责任', '要求贷款资金先到B账户再转出', '贷后又以合规检查名义收费'],
    suggestions: ['不要替他人申请本人名下贷款', '核实贷款合同的借款主体', '遇到贷后收费及时向监管或警方反映'],
    timeline: [
      { time: '申请前', event: 'A因资质不足无法获得贷款' },
      { time: '中介介入', event: '中介安排B以本人名义申请贷款' },
      { time: '资金转移', event: '贷款资金由A实际使用' },
      { time: '风险暴露', event: 'A违约后，B承担还款和征信后果' },
    ],
    sourceName: '北京金融监管局消费者风险提示',
    sourceUrl: 'https://www.bankofchina.com/bocins/cusser/cs5/202510/t20251031_25549788.html',
    credibility: '高',
  },
  {
    id: 'case-industry-006',
    title: '多地媒体调查：AB贷呈现团伙化、标准化灰产链',
    city: '多地',
    region: '全国',
    scamType: '助贷灰产链',
    riskLevel: '中',
    progress: '待核验',
    amountLoss: 43000,
    publishedAt: '2026-05-01',
    updatedAt: '2026-06-10',
    summary: '媒体调查称，AB贷需求端是征信不良或资质不足的A，工具端是被人情绑架、征信较好的B，中介端多为无资质团伙，流程和话术趋于标准化。',
    pattern: ['精准获客', '话术标准化', '注销公司逃避追责'],
    warningSignals: ['“紧急联系人”变共同借款', '称6个月后与B无关', '服务公司收取高比例中介费'],
    suggestions: ['识别“紧急联系人/监管人”话术', '谨慎参加线下助贷面谈', '保存门店、合同、收费凭证用于举报'],
    timeline: [
      { time: '获客', event: '黑中介筛选资质不足且急需资金的A' },
      { time: '找B', event: 'A以人情请求B担任担保人、监管人或紧急联系人' },
      { time: '包装', event: '中介安排B查询征信、签署材料、刷脸面签' },
      { time: '收割', event: '贷款到账后向A或B收取高比例服务费，风险留给B' },
    ],
    sourceName: '21经济网/界面新闻调查报道',
    sourceUrl: 'https://www.21jingji.com/article/20260501/herald/40906a6b40d7d75864454929c3847af1.html',
    credibility: '中',
  },
]
