import type { FraudCase } from '@/types/case'

export const FRAUD_CASES: FraudCase[] = [
  {
    id: 'case-sh-001',
    title: '上海：短视频“军官贷”引流后多笔骗贷',
    city: '上海市',
    region: '华东',
    scamType: '冒充军官贷',
    riskLevel: '高',
    progress: '立案中',
    amountLoss: 780000,
    publishedAt: '2024-03-10',
    updatedAt: '2026-04-01',
    summary: '受害者在短视频平台添加“军官贷”客服后，被引导连续申请多笔贷款，资金被转移。',
    pattern: ['先收费再放款', '伪造身份背书', '多平台分散借款'],
    warningSignals: ['催促立即操作', '要求提供验证码', '承诺“100%下款”'],
    suggestions: ['立刻停止转账', '向平台与警方同步举报', '保留聊天和转账证据'],
    timeline: [
      { time: '2024-02-01', event: '在短视频平台看到低息贷款广告并添加客服' },
      { time: '2024-02-03', event: '被要求提交征信与身份信息，办理首笔贷款' },
      { time: '2024-02-06', event: '以“额度激活”为由再次借款并转账' },
      { time: '2024-02-09', event: '客服失联，受害者报案' },
    ],
    sourceName: '央视新闻（案例整理）',
    sourceUrl: 'https://news.cctv.com/2023/03/21/ARTI4jfYLiT3HUG9E8k7WDFZ230321.shtml',
    credibility: '高',
  },
  {
    id: 'case-ah-002',
    title: '安徽：大学生“提额贷”陷入连环借贷',
    city: '合肥市',
    region: '华东',
    scamType: '征信提额贷',
    riskLevel: '高',
    progress: '立案中',
    amountLoss: 300000,
    publishedAt: '2024-01-18',
    updatedAt: '2026-03-21',
    summary: '犯罪团伙以“提高信用”为名，诱导大学生分批贷款并转入指定账户。',
    pattern: ['征信修复话术', '分批借款', '伪造客服流程'],
    warningSignals: ['让受害者签“保密协议”', '要求下载远程协助软件', '多次小额转账测试'],
    suggestions: ['卸载远程控制软件', '修改金融账户密码', '向学校与警方同步报备'],
    timeline: [
      { time: '2024-01-02', event: '通过QQ群接触“信用提额服务”' },
      { time: '2024-01-05', event: '被指导申请多家网贷平台' },
      { time: '2024-01-09', event: '以“风控解除”为由持续转账' },
      { time: '2024-01-11', event: '资金无法追回，报案' },
    ],
    sourceName: '地方反诈中心通报（整理）',
    sourceUrl: 'https://www.chinacourt.org/article/detail/2024/02/id/7372912.shtml',
    credibility: '中',
  },
  {
    id: 'case-gd-003',
    title: '广东：假担保公司收取保证金后失联',
    city: '深圳市',
    region: '华南',
    scamType: '保证金诈骗',
    riskLevel: '高',
    progress: '待核验',
    amountLoss: 120000,
    publishedAt: '2025-06-10',
    updatedAt: '2026-04-07',
    summary: '诈骗方要求受害者向“担保公司”先缴纳保证金，款项到账后即拉黑。',
    pattern: ['虚假担保机构', '私户收款', '合同条款模糊'],
    warningSignals: ['收款账户与公司名不一致', '拒绝线下见面核验', '反复更换客服'],
    suggestions: ['核对收款账户主体', '拒绝向个人账户付款', '留存合同与网页快照'],
    timeline: [
      { time: '2025-06-10', event: '在搜索引擎点击贷款广告' },
      { time: '2025-06-11', event: '签订电子合同并支付保证金' },
      { time: '2025-06-12', event: '对方要求继续缴纳“解冻金”' },
      { time: '2025-06-12', event: '受害者拒绝后被拉黑' },
    ],
    sourceName: '用户线索平台汇总',
    sourceUrl: 'https://finance.sina.com.cn/chanjing/b/2023-05-15/doc-imytqsvm1855086.shtml',
    credibility: '中',
  },
  {
    id: 'case-js-004',
    title: '江苏：伪造银行内审流程实施 AB 贷',
    city: '南京市',
    region: '华东',
    scamType: '伪造银行流程',
    riskLevel: '中',
    progress: '立案中',
    amountLoss: 86000,
    publishedAt: '2025-08-22',
    updatedAt: '2026-03-30',
    summary: '诈骗团伙伪造“银行内审”流程，要求受害者分阶段转账验证资质。',
    pattern: ['伪造官方流程', '阶段性付费', '制造紧迫感'],
    warningSignals: ['使用个人微信沟通所谓“内审”', '无法提供工号核验渠道', '通话中规避录音'],
    suggestions: ['通过银行官方热线核验', '拒绝任何线下转账验证', '报警并冻结可疑收款账户'],
    timeline: [
      { time: '2025-08-20', event: '收到“银行贷款专员”来电' },
      { time: '2025-08-21', event: '按要求支付“资质验证金”' },
      { time: '2025-08-22', event: '继续被要求支付“账户激活费”' },
      { time: '2025-08-22', event: '察觉异常后终止并报警' },
    ],
    sourceName: '地方警方案例整理',
    sourceUrl: 'https://news.cctv.com/2023/03/21/ARTI4jfYLiT3HUG9E8k7WDFZ230321.shtml',
    credibility: '高',
  },
  {
    id: 'case-zj-005',
    title: '浙江：电商商家被“刷流水提额”骗贷',
    city: '杭州市',
    region: '华东',
    scamType: '刷流水诈骗',
    riskLevel: '中',
    progress: '已判决',
    amountLoss: 64000,
    publishedAt: '2025-02-14',
    updatedAt: '2026-02-28',
    summary: '商家被诱导在指定平台开户刷流水，后被套取贷款额度。',
    pattern: ['刷流水提额', '假平台对账', '资金闭环转移'],
    warningSignals: ['要求重复转入同一账户', '平台域名异常', '客服回避合同细节'],
    suggestions: ['立即停止刷流水操作', '核验平台备案信息', '保存网页与交易记录'],
    timeline: [
      { time: '2025-02-01', event: '接触“店铺贷款提额”推广' },
      { time: '2025-02-03', event: '按照要求多次转入指定账户' },
      { time: '2025-02-05', event: '发现账户被盗刷并报警' },
      { time: '2025-07-18', event: '案件进入司法审理阶段' },
    ],
    sourceName: '法院公开信息整理',
    sourceUrl: 'https://www.chinacourt.org/article/detail/2024/02/id/7372912.shtml',
    credibility: '高',
  },
  {
    id: 'case-sc-006',
    title: '四川：冒充“金融监管中心”要求解冻费',
    city: '成都市',
    region: '西南',
    scamType: '解冻金诈骗',
    riskLevel: '中',
    progress: '待核验',
    amountLoss: 38000,
    publishedAt: '2025-11-01',
    updatedAt: '2026-04-10',
    summary: '嫌疑人冒充监管人员称贷款被冻结，需缴纳解冻金后放款。',
    pattern: ['冒充监管机构', '恐吓冻结账户', '制造权威压迫'],
    warningSignals: ['使用非官方邮箱发送通知', '文书格式错误', '拒绝官方回访核验'],
    suggestions: ['仅通过官方公开电话核验', '拒绝任何“解冻费”转账', '保留电话录音和截图'],
    timeline: [
      { time: '2025-10-28', event: '收到“监管中心”来电' },
      { time: '2025-10-29', event: '按指示转账“解冻费”' },
      { time: '2025-10-30', event: '对方要求继续补缴“风控金”' },
      { time: '2025-10-30', event: '受害者中止并举报' },
    ],
    sourceName: '用户线索平台汇总',
    sourceUrl: 'https://finance.sina.com.cn/chanjing/b/2023-05-15/doc-imytqsvm1855086.shtml',
    credibility: '中',
  },
]
